
# html lang
language: zh-CN

# header
site_brand_name: Ivy

logo_image:
  enable: true
  avatar_path: /avatar.png
  github_image_path: /github-mark.png
  github_path: https://github.com/ivorysillegalss
  jeujin_image_path: /juejin.png
  juejin_path: https://juejin.cn/user/3353932733889884


menu:
  Home: /
  Archive: /archives/
  Gallery: /categories/gallery/
  Projects: /projects/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: Ivorysillegal's Blog
  sign: I have a room full of mirrors so I can be surrounded by winners.
  body:
    - Wish U All Have Super Cow Power.
  fortune:
    - 人类本身不擅长数学严格 
    - 于是创建了程序
    - 程序本身是数学严格的
    - 通过辅助人类进行数学严格的工作
    - 使人类世界更好实现数学严格的需求
  image: /profile_cover.jpg


  links:
    Home: /
    Blogs: /archives/
    Projects: /projects/

footer:
  copyright_info:
    enable: true
    author: © ivy_czc

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: true
    content: Love Yourself.

  contact_info:
    enable: true
    email: chenzczczc@gmail.com
    vx: ivorisillegal

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false

# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: false
  appId: # Your valine app Id
  appKey: # Your valine app Key
  lang: 'en'
  placeholder: 'Say something'
  avatar: 'mp'
  meta: ['nick', 'mail']

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'en'

# local search
local_search:
  enable: false
  place_holder: Search Anything
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: false # unescape html strings to the readable one
  preload: false # reload the search data when the page loads, this will accelerate the search process
